import './globals.css'
import '@mantine/core/styles.css';
import type { Metadata } from 'next'
import { MantineProvider, ColorSchemeScript, Stack } from '@mantine/core';
import { Inter } from 'next/font/google'
import { Navigator } from '../components/Navigator';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><ColorSchemeScript /></head>
      <body className={`${inter.className} bg-white`}>
        <MantineProvider>
          <Stack className="w-[800px] m-0 mx-auto p-6" align="center">
            <nav><Navigator /></nav>
            <main>
              {children}
            </main>
          </Stack>
        </MantineProvider>
      </body>
    </html>
  )
}
